function allSets = getInput2(x)

if nargin<1
    x = 'init';	
end

persistent handles conDef

switch x
    
    %  Setup the screen	
    case 'init'
        cellTypes = {'rod' 'lCone' 'mCone' 'sCone' 'uvCone'};
        if exist('playVars.mat')
            load playVars
        else
            infoDef = {'Comment','Label','2'};
            numDef = {'4'};
            conDef{1} = {'0','amp','0'};
            conDef{2} = {'19.3','red','0'};
            conDef{3}= {'30','orange','0'};
            conDef{4} = {'8.18','blue','0'};
            typeDef = 1;
        end
        fig2 = figure('MenuBar','none', ...
            'Units','normalized', ...    
            'Position',[0.2 0.2 0.5 0.5], ...
            'Tag','Fig2');
        %  Title
        h1 = uicontrol('Parent',fig2, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',24, ...
            'Units','normalized', ...
            'Position',[.1 .9 .9 .1], ...
            'String','For This CellInfo', ...
            'Style','text', ...
            'Tag','title');
        %  Create buttons, boxes, and labels
        %  First box is an editable text, in which user inputs the label
        h2 = uicontrol('Parent',fig2, ...
            'Units','normalized', ...
            'Position',[.5 .85 .25 0.05], ...
            'String',infoDef{1}, ...
            'Style','edit', ...
            'Tag','comment');
        %  This is the label for the previous editable text box
        h3 = uicontrol('Parent',fig2, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units','normalized', ...
            'Position',[.1 .8 .4 .1], ...
            'String','Comment', ...
            'Style','text', ...
            'Tag','StaticText1');
        %  label
        h4 = uicontrol('Parent',fig2, ...
            'Units','normalized', ...
            'Position',[.5 .75 .25 .05], ...
            'String',infoDef{2}, ...
            'Style','edit', ...
            'Tag','label');
        %  This is the label for the previous editable text box
        h5 = uicontrol('Parent',fig2, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units','normalized', ...
            'Position',[.1 .7 .4 .1], ...
            'String','Label', ...
            'Style','text', ...
            'Tag','StaticText1');
        %  which rig
        h6 = uicontrol('Parent',fig2, ...
            'Units','normalized', ...
            'Position',[.5 .65 .25 .05], ...
            'String',infoDef{3}, ...
            'Style','edit', ...
            'Tag','rig');
        %  This is the label for the previous editable text box
        h7 = uicontrol('Parent',fig2, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units','normalized', ...
            'Position',[.1 .6 .4 .1], ...
            'String','Experimental Rig:', ...
            'Style','text', ...
            'Tag','StaticText1');
        %  First box is an editable text, in which user inputs the label
        h8 = uicontrol('Parent',fig2, ...
            'Units','normalized', ...
            'Position',[.5 .55 .25 .05], ...
            'String',numDef, ...
            'Style','edit', ...
            'Tag','output');
        %  This is the label for the previous editable text box
        h9 = uicontrol('Parent',fig2, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units','normalized', ...
            'Position',[.1 .5 .4 .1], ...
            'String','How many OutputScaleFactors?', ...
            'Style','text', ...
            'Tag','StaticText1');
        %  First box is an editable text, in which user inputs the label
        h10 = uicontrol('Parent',fig2, ...
            'Max', 1, ...
            'Units','normalized', ...
            'Position',[.57 .3 .1 .2], ...
            'String',cellTypes, ...
            'Style','listbox', ...
            'Tag','cellType', ...
            'Value',typeDef);       
        %  This is the label for the previous listbox
        h11 = uicontrol('Parent',fig2, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units','normalized', ...
            'Position',[.1 .4 .4 .1], ...
            'String','What cell type?', ...
            'Style','text', ...
            'Tag','StaticText1');
        
        %  This is the button to press to return to playtime
        h12 = uicontrol('Parent',fig2, ...
            'Units','normalized', ...
            'Callback','getInput2 numInputs', ...
            'Position',[.3 .1 .3 .1], ...
            'String','Push to Continue', ...
            'Tag','cont');
        uiwait  
        
    case 'numInputs'
        uiresume
        b1 = findobj(gcf,'tag','comment');
        c1 = findobj(gcf,'tag','label');
        d1 = findobj(gcf,'tag','rig');
        e1 = findobj(gcf,'tag','cellType');
        handles.comment = get(b1,'String');
        handles.label = get(c1,'String');
        handles.rig = get(d1,'String');
        handles.type = get(e1,'Value');
        f1 = findobj(gcf,'tag','output');
        strlen = get(f1,'String');
        strlen = char(strlen);
        strlen = str2num(strlen);
        if strlen > length(conDef)
            conDef{1} = {'0','amp','0'};
            conDef{2} = {'19.3','red','0'};
            conDef{3}= {'30','orange','0'};
            conDef{4} = {'8.18','blue','0'};
        end
        delete(gcf)        
        x = (1 - .4/strlen)/strlen/4;
        searchstring = {'OutputScaleFactor','OutputConfiguration','NDFConfiguration:'};
        fig3 = figure('MenuBar','none', ...
            'Units','normalized', ...    
            'Position',[0.2 0.2 0.5 0.2*strlen], ...
            'Tag','Fig2');
        %  Title
        y = 1 - (0.25/strlen);
        h1 = uicontrol('Parent',fig3, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',24, ...
            'Units','normalized', ...
            'Position',[.1 y .9 .2/strlen], ...
            'String','For This CellInfo', ...
            'Style','text', ...
            'Tag','title');
        j = 0;
        for i = 1:strlen
            % OutputScaleFactor
            osf = uicontrol('Parent',fig3, ...
                'Units','normalized', ...
                'Position',[.5 y-(4*i-3)*x .3 .15*1/strlen], ...
                'String',conDef{i}{1}, ... 
                'Style','edit', ...
                'Tag','allInputs', ...
                'Userdata',j);
            j = j + 1;
            %  This is the label for the previous editable text box
            osf2 = uicontrol('Parent',fig3, ...
                'BackgroundColor',[0.8 0.8 0.8], ...
                'Units','normalized', ...
                'Position',[.1 y-(4*i-3)*x .4 0.15*1/strlen], ...
                'String',searchstring{1}, ...
                'Style','text', ...
                'Tag','StaticText1');
            %  OutputConfiguration
            oc = uicontrol('Parent',fig3, ...
                'Units','normalized', ...
                'Position',[.5 y-(4*i-2)*x .3 0.15*1/strlen], ...
                'String',conDef{i}{2}, ... 
                'Style','edit', ...
                'Tag','allInputs', ...
                'Userdata',j);
            j = j + 1;
            %  This is the label for the previous editable text box
            oc2 = uicontrol('Parent',fig3, ...
                'BackgroundColor',[0.8 0.8 0.8], ...
                'Units','normalized', ...
                'Position',[.1 y-(4*i-2)*x .4 0.15*1/strlen], ...
                'String',searchstring{2}, ...
                'Style','text', ...
                'Tag','StaticText1');
            %  NDFConfiguration
            ndf = uicontrol('Parent',fig3, ...
                'Units','normalized', ...
                'Position',[.5 y-(4*i-1)*x .3 0.15*1/strlen], ...
                'String',conDef{i}{3}, ... 
                'Style','edit', ...
                'Tag','allInputs', ...
                'Userdata',j);
            j = j + 1;
            %  This is the label for the previous editable text box
            ndf2 = uicontrol('Parent',fig3, ...
                'BackgroundColor',[0.8 0.8 0.8], ...
                'Units','normalized', ...
                'Position',[.1 y-(4*i-1)*x .4 0.15*1/strlen], ...
                'String',searchstring{3}, ...
                'Style','text', ...
                'Tag','StaticText1');
        end
        %  This is the button to press to return to playtime
        h6 = uicontrol('Parent',fig3, ...
            'Units','normalized', ...
            'Callback','getInput2 allDone', ...
            'Position',[.35 .02 .3 .2/strlen], ...
            'String','Push when done', ...
            'Tag','done');
        uiwait
    case 'allDone'
        sametag = findobj(gcf,'Tag','allInputs');
        strdata = get(sametag,'string');  
        j = length(strdata);
        strlen = j/3;
        for i = 1:strlen
            handles.allInputs{i} = {strdata{j} strdata{j-1} strdata{j-2}};
            j = j - 3;
        end
        uiresume
        delete(gcf)
end

allSets = handles;
infoDef = {handles.comment handles.label handles.rig};
numDef = length(handles.allInputs);
conDef = handles.allInputs;
typeDef = handles.type;

save playVars infoDef numDef conDef typeDef