function varargout = getInput(varargin)

persistent handles labDef decDef

if nargin<2
	x=varargin{1};
else
    [x,labDef,decDef] = deal(varargin{1:3});
end

switch x
    
    %  Setup the screen	
    case 'init'
        fig2 = figure('MenuBar','none', ...
        'Units','normalized', ...    
        'Position',[0.2 0.2 0.5 0.5], ...
            'Tag','Fig2');
        %  Title
        h1 = uicontrol('Parent',fig2, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',24, ...
            'Units','normalized', ...
            'Position',[.1 .8 .8 .1], ...
            'String','For This Condition', ...
            'Style','text', ...
            'Tag','title');
        %  Create buttons, boxes, and labels
        %  First box is an editable text, in which user inputs the label
        h2 = uicontrol('Parent',fig2, ...
            'Units','normalized', ...
            'Position',[.5 .55 .25 .05], ...
            'String',labDef, ...
            'Style','edit', ...
            'Tag','label');
        %  This is the label for the previous editable text box
        h3 = uicontrol('Parent',fig2, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units','normalized', ...
            'Position',[.1 .5 .4 .1], ...
            'String','Type in the label for this search', ...
            'Style','text', ...
            'Tag','StaticText1');
        %  how much to decimate
        h4 = uicontrol('Parent',fig2, ...
            'Units','normalized', ...
            'Position',[.5 .35 .25 .05], ...
            'String',decDef, ...
            'Style','edit', ...
            'Tag','decimate');
        %  This is the label for the previous editable text box
        h5 = uicontrol('Parent',fig2, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units','normalized', ...
            'Position',[.1 .3 .4 .1], ...
            'String','How much to decimate for this condition:', ...
            'Style','text', ...
            'Tag','StaticText1');
        %  This is the button to press to return to playtime
        h6 = uicontrol('Parent',fig2, ...
            'Units','normalized', ...
            'Callback','getInput allDone', ...
            'Position',[.3 .1 .3 .1], ...
            'String','Push when done', ...
            'Tag','done');
            uiwait  
    case 'allDone'
        f1 = findobj(gcf,'tag','label');
        c1 = findobj(gcf,'tag','decimate');
        handles.label = get(f1,'String');
        handles.decimate = get(c1,'String');
        uiresume
        delete(gcf)
end
varargout{1} = handles.label;
varargout{2} = handles.decimate;